flags:
  reflex-dom:
    webkit2gtk: false
extra-package-dbs: []
packages:
- '.'
- location:
    git: https://github.com/reflex-frp/reflex
    commit: 2fe0f566f8d6b6eceb178a85516643390111bb83
  extra-dep: true
- location:
    git: https://github.com/reflex-frp/reflex-dom.git
    commit: 644b1a056f6689bdf6c0eed83cce576889a14284
  subdirs:
  - reflex-dom
  - reflex-dom-core
  extra-dep: true
- location:
    git: https://github.com/mokus0/dependent-sum.git
    commit: 02173260ce60113ac442da04bf40139119271380
  extra-dep: true
- location:
    git: https://github.com/afcady/dependent-sum-template.git
    commit: 68fc1a90580ea8f20775491cf651eefea422212a
  extra-dep: true
- location:
    git: https://github.com/gtk2hs/gtk2hs.git
    commit: 21d3a12a82756d04066e5e4198b35097012ee65b
  subdirs:
  - cairo
  - gio
  - glib
  - gtk
  - pango
  - tools
  extra-dep: true
- location:
    git: https://github.com/byorgey/hashtables.git
    commit: 47d9ed261a5aba66a13d3c4da0e391d338b57fc5
  extra-dep: true
extra-deps:
- cpphs-1.20.5
- ghcjs-dom-0.8.0.0
- ghcjs-dom-jsaddle-0.8.0.0
- haskell-src-exts-1.17.1
- haskell-src-meta-0.6.0.14
- hlint-1.9.35
- jsaddle-0.8.3.2
- jsaddle-dom-0.8.0.0
- jsaddle-warp-0.8.3.1
- jsaddle-webkitgtk-0.8.3.1
- prim-uniq-0.1.0.1
- primitive-0.6.2.0
- ref-tf-0.4.0.1
- vector-0.12.0.0
- zenc-0.1.1
resolver: lts-8.3
